2015-11-29 16:07:40,414 - __main__ - INFO - Hello baby
2015-11-29 16:08:41,037 - __main__ - INFO - Hello baby
2015-11-29 16:08:41,037 - __main__ - ERROR - Hello baby
2015-11-29 16:19:06,870 - __main__ - INFO - Hello baby
2015-11-29 16:19:06,870 - __main__ - ERROR - Hello baby
2015-11-29 16:19:06,870 - __main__ - ERROR - Failed to open file
Traceback (most recent call last):
  File "./logging_test.py", line 24, in <module>
    open('/path/to/does/not/exist', 'rb')
IOError: [Errno 2] No such file or directory: '/path/to/does/not/exist'
2015-11-29 16:36:36,951 - __main__ - INFO - Hello baby
2015-11-29 16:36:36,968 - __main__ - ERROR - Hello baby
2015-11-29 16:36:36,968 - __main__ - ERROR - Failed to open file
Traceback (most recent call last):
  File "./logging_test.py", line 24, in <module>
    open('/path/to/does/not/exist', 'rb')
IOError: [Errno 2] No such file or directory: '/path/to/does/not/exist'
2015-11-29 16:43:51,847 - __main__ - INFO - Hello baby
2015-11-29 16:43:51,848 - __main__ - ERROR - Hello baby
2015-11-29 16:43:51,848 - __main__ - ERROR - Failed to open file
Traceback (most recent call last):
  File "./logging_test.py", line 24, in <module>
    open('/path/to/does/not/exist', 'rb')
IOError: [Errno 2] No such file or directory: '/path/to/does/not/exist'
2015-11-29 16:43:51,849 - __main__ - INFO - An info message with some parameters
2015-11-29 16:43:59,791 - __main__ - INFO - Hello baby
2015-11-29 16:43:59,791 - __main__ - ERROR - Hello baby
2015-11-29 16:43:59,792 - __main__ - ERROR - Failed to open file
Traceback (most recent call last):
  File "./logging_test.py", line 24, in <module>
    open('/path/to/does/not/exist', 'rb')
IOError: [Errno 2] No such file or directory: '/path/to/does/not/exist'
2015-11-29 16:43:59,793 - __main__ - INFO - An info message with some parameters
2015-11-29 16:44:47,976 - __main__ - INFO - Hello baby
2015-11-29 16:44:47,976 - __main__ - ERROR - Hello baby
2015-11-29 16:44:47,976 - __main__ - ERROR - Failed to open file
Traceback (most recent call last):
  File "./logging_test.py", line 24, in <module>
    open('/path/to/does/not/exist', 'rb')
IOError: [Errno 2] No such file or directory: '/path/to/does/not/exist'
2015-11-29 16:44:47,978 - __main__ - INFO - An info message with some parameters
